### PR TITLE
Static site initial commit

### LINKED ISSUE #1: Build a static website
Something we can point to. I think that osmontreal.ca would work well.

### PR DESCRIPTION
**Pull request by khos2ow**
This PR fixes #1

### CODE REVIEW

**Comment by khos2ow** [comment]
@RichardLitt ping for review. Can you add me to the project and/or repo?

**Comment by RichardLitt** [comment]
Hey! This looks great! I love the work you've done. Sorry for the delay: I've been traveling. 

I have two things I want to discuss before merging. 1: this makes it _harder_ for people to contribute. Can you include really clear steps for how to do this while using only the GitHub interface? I want to make this as easy as opening a PR. Maybe a paragraph saying: "If you can't figure this out, open an issue with your information, and we can handle it for you!"

Secondly: This makes the initial README no longer have the information. Is there any way to make the README sync to the website? One of the benefits of having a list on GitHub is that it is easy to search, and easy to add to. Going off-GitHub means that people are less likely to add stuff. I want it to be part of the Markdown world, not just locked on another website. What do you think about this? 

Thirdly: Can you make the text pop on the "A directory of companies, people, and projects that are Open Source and from Montréal." tagline? Hard to read right now!

Otherwise, this is great!

**Comment by khos2ow** [comment]
I created [CONTRIBUTING.md](https://github.com/khos2ow/montreal/blob/static-site/CONTRIBUTING.md) for the exact same reason.

On the other hand, I actually totally agree with your points! I cannot think of a (at least easy) way to sync README with content of `/data` folder.

I guess what we can do for this is to revert back README to previous state, and change the contributing guide in a sense that if one needs to add something either they:

- do the full thing themselves (add a yml file in `/data/<section>` and update README)
- update only README and us -as maintainers- add the corresponding yml file
- create an addition request issue and us -as maintainers- add the yml file and update README

**Comment by khos2ow** [comment]
@RichardLitt what do you think?

**Comment by RichardLitt** [comment]
Thanks Khosrow. I haven't had adequate time to get to this, today. I'll
respond as soon as I am able.

**Comment by RichardLitt** [comment]
Sorry for the delay!

I think what you suggest makes the most sense - why don't we ask them to the the YML edits, and if they don't, we can do it ourselves. Do you want to add that to this PR? After that,  think this is good to go!

**Comment by khos2ow** [comment]
Yes, I will do that shortly.
When this PR gets merged we can move on to other repos as well (opensourcecities.github.io, toronto, vancouver, etc)

**Comment by khos2ow** [comment]
@RichardLitt It's ready, let's do this!

**Comment by RichardLitt** [comment]
Merged!!!! Thank you! 🎉

**Pull request merged**
