### PR TITLE
Add photos of October 2019 meetup

### PR DESCRIPTION
**Pull request by khos2ow**

### CODE REVIEW

**Comment by RichardLitt** [comment]
Woo!

**Comment by khos2ow** [comment]
Yes @RichardLitt, that happened and we missed you!

**Comment by RichardLitt** [comment]
Next time let me know. It is not a long drive for me. :)

**Comment by khos2ow** [comment]
Definitely! @ruyadorno are you up to for organizing the next one? :wink:

**Comment by ruyadorno** [comment]
oh yeah, we have a special Node.js planned for the 9 December, I'll add it to meetup.com soon

we're going to take advantage of the timing, with the [big node.js conf happening in Montreal](https://events19.linuxfoundation.org/events/nodejs-interactive-2019/) in that same week

**Comment by RichardLitt** [comment]
$700 is a lot. O.o

**Comment by ruyadorno** [comment]
ooohh, for the conference? meh it's a big conf, they're all crazy expensive these days but anyways, that's beside the point, the point I was making is that we're taking advantage of the fact that we have all this people coming to town anyways 🤷‍♂ 

but hey, the node.js foundation do host the collaboration summit in the two days after the conference (13-14 December) and that one should be free (you should know about that one, you have been involved with the foundation for a while in the past, I remember seeing your face in the discussions there 😊 )

**Comment by RichardLitt** [comment]
I can't make it on the 14th, unfortunately. Should be fun, though. Yes, I used to be involved in Node a bit more. :) Saw you on npm recently - good work on the npm fund stuff! Didn't realize you worked with them now.

**Comment by ruyadorno** [comment]
thanks! ❤️ yeah, it has been 2 months now, I'm loving it!

**Pull request merged**
