### PR TITLE
Externalize them to standalone repo

### LINKED ISSUE #43: Permalink of contents
It would be cool to have a permalink of contents published on the site (orgs, users, ...). Something like:

- `https://opensourcecities.github.io/montreal/users/<name>`
- `https://opensourcecities.github.io/montreal/orgs/<name>`

This will give us the ability to have some kind of a _profile_ on the site and make the content shareable. To have this feature, I need to have a small-ish redesign of the hugo based site.

### PR DESCRIPTION
**Pull request by khos2ow**
Fixes #43

### CODE REVIEW

**Comment by khos2ow** [comment]
@RichardLitt @ruyadorno this is done, but I'm having second thought to include theme as external git submodule. Because it forces users to know beforehand there will be a submodule to do a `git clone --recurse-submodules ...` to fork and clone.

On the other hand we should always change the theme directly on its own repo and manually push the changes in standalone commits in the site(s).

What do you think?

**Comment by khos2ow** [comment]
and the repo in question is this: https://github.com/opensourcecities/osc-theme/tree/master

**Comment by RichardLitt** [comment]
I think it's only a problem if it's undocumented. Add a note to the README, and we're good. 

Users simply adding content should never have to download the submodule, though. Is this a requirement, at the moment?

**Comment by khos2ow** [comment]
No, not a requirement, but if they want to run `hugo server` locally then it works, but nothing will be shown in browser. I agree about documenting though.

**Comment by ruyadorno** [comment]
🎉

**Pull request merged**
