### PR TITLE
techconf.ca

### PR DESCRIPTION
**Pull request by lanisys-solutions**
Adding techconf.ca an open source project created by Montrealers.

### CODE REVIEW

**Comment by RichardLitt** [comment]
Thanks!

**Comment by lanisys-solutions** [comment]
Thanks!

When will it be deployed to GitHub Pages?

**Comment by RichardLitt** [comment]
I'm not sure. I'm not actively maintaining this at the moment.

**Comment by lanisys-solutions** [comment]
Looks like the Travis CI bot is no longer working and it doesn't automatically publishes the site to `gh-pages`.

**Comment by RichardLitt** [comment]
Cool. @khos2ow?

**Pull request merged**
