### PR TITLE
WIP: Enhance travis

### PR DESCRIPTION
**Pull request by khos2ow**

### CODE REVIEW

**Comment by RichardLitt** [comment]
What does the dangerfile do?

**Comment by khos2ow** [comment]
It seems you can check/validate the "conventions" you want to set. In this particular case there's an integration between awesome_bot and Danger to report back errors to the PR.

Since we're going to allow `302` status, I thought it would be a good idea to have a visibility of them, because there might be some cases which 302 wouldn't be acceptable.

**Comment by khos2ow** [comment]
Once setup, there won't be any additional complexity, on the other hand I think it will kinda simplify the process. If Travis fails it pushes back a comment to the PR as [this](https://github.com/dkhamsing/awesome_bot#danger) which we can immediately see what's going on.

**Comment by RichardLitt** [comment]
Alright then!

**Comment by khos2ow** [comment]
NO, it wasn't complete yet!! Reverted the merge.

**Comment by RichardLitt** [comment]
Ah! 

Can you start naming your PRs which aren't complete as `WIP`? Otherwise, I'll assume it is ready to merge; otherwise, the act of a PR itself signals that it is done.

**Comment by khos2ow** [comment]
The name of this PR still contains `WIP` :wink: 
and btw I added a label too [work-in-progress](https://github.com/opensourcecities/montreal/labels/work-in-progress)

**Pull request merged**
